[package]
name = "chat_app"
description = "From October 2021 Rust Linz"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version= "1", features = ["full"] }
tokio-stream = "0.1.11"
futures-util = "0.3"
warp = "0.3"